
wildfly:
  build: ./activiti
  container_name: "wildfly"
  ports:
    - "8080:8080"
    - "9990:9990"
#  volumes:
#    - "./deployments:/opt/jboss/wildfly/standalone/deployments"

postgres:
  image: postgres:9.3
  container_name: "postgres"
  ports:
    - "5432:5432"
  volumes:
    - "./postgres:/docker-entrypoint-initdb.d"
  environment:
    - "POSTGRES_PASSWORD=postgres"
    - "PGPASSWORD=postgres"

# ActiveMQ:61616 => "admin":"adminactivemq"
# ActiveMQWeb:8161 => "admin":"admin"
activemq:
  image: rmohr/activemq:5.10.0
  container_name: "activemq"
  ports:
    - "61616:61616"
    - "8161:8161"